# Plot Global Mean Thermosteric Sea Level

### Test the pathlib library

In [1]:
from pathlib import Path
import numpy as np
from scipy import signal
import xarray as xr

/Users/dewilebars/anaconda3/envs/p37ds/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


In [42]:
p = Path('../SLProj/')
[x for x in p.iterdir()] #if x.is_dir() -> What is that?

[PosixPath('../SLProj/LICENSE'),
 PosixPath('../SLProj/code'),
 PosixPath('../SLProj/README.md'),
 PosixPath('../SLProj/namelists'),
 PosixPath('../SLProj/ref_results'),
 PosixPath('../SLProj/.gitignore'),
 PosixPath('../SLProj/figures'),
 PosixPath('../SLProj/.ipynb_checkpoints'),
 PosixPath('../SLProj/.git'),
 PosixPath('../SLProj/outputs'),
 PosixPath('../SLProj/notebooks'),
 PosixPath('../SLProj/reports')]

In [55]:
list(p.glob('*/*/*'))[0].parts[4]

'mod_main.cpython-37.pyc'

In [49]:
p.glob('*/*/*')[1].parts # This gives only the commnon part of the path

TypeError: 'generator' object is not subscriptable

In [33]:
year_min = 1986  # Included
year_max = 2100  # Excluded (2101)
time_all = np.arange(year_min, year_max)+0.5
time_all

array([1986.5, 1987.5, 1988.5, 1989.5, 1990.5, 1991.5, 1992.5, 1993.5,
       1994.5, 1995.5, 1996.5, 1997.5, 1998.5, 1999.5, 2000.5, 2001.5,
       2002.5, 2003.5, 2004.5, 2005.5, 2006.5, 2007.5, 2008.5, 2009.5,
       2010.5, 2011.5, 2012.5, 2013.5, 2014.5, 2015.5, 2016.5, 2017.5,
       2018.5, 2019.5, 2020.5, 2021.5, 2022.5, 2023.5, 2024.5, 2025.5,
       2026.5, 2027.5, 2028.5, 2029.5, 2030.5, 2031.5, 2032.5, 2033.5,
       2034.5, 2035.5, 2036.5, 2037.5, 2038.5, 2039.5, 2040.5, 2041.5,
       2042.5, 2043.5, 2044.5, 2045.5, 2046.5, 2047.5, 2048.5, 2049.5,
       2050.5, 2051.5, 2052.5, 2053.5, 2054.5, 2055.5, 2056.5, 2057.5,
       2058.5, 2059.5, 2060.5, 2061.5, 2062.5, 2063.5, 2064.5, 2065.5,
       2066.5, 2067.5, 2068.5, 2069.5, 2070.5, 2071.5, 2072.5, 2073.5,
       2074.5, 2075.5, 2076.5, 2077.5, 2078.5, 2079.5, 2080.5, 2081.5,
       2082.5, 2083.5, 2084.5, 2085.5, 2086.5, 2087.5, 2088.5, 2089.5,
       2090.5, 2091.5, 2092.5, 2093.5, 2094.5, 2095.5, 2096.5, 2097.5,
      

In [34]:
for j in range(2):
    print(j)

0
1


In [57]:
#Ordering strings:
al = ['v20130719', 'v20110929']
al

['v20130719', 'v20110929']

In [59]:
al.sort()
al

['v20110929', 'v20130719']

In [67]:
vs = []
for k in range(3):
    vs.append('rs')
vs

['rs', 'rs', 'rs']

In [70]:
a1 = np.array([1,2,3])
a2 = np.ones(2)
a2 = np.append(a1,a2)
a2

array([1., 2., 3., 1., 1.])

In [81]:
a = [1, 2, 3]
b = [1, 2, 4]
c = b
if a in (b, c):
    print('Yes')


In [87]:
a = np.array([1, 2, 3, 4, np.nan, np.nan])
np.sum(np.isnan(a))

2

In [96]:
# Detrending test: Use scipy.detrend 
a = np.arange(10)
A = np.array([a,a,a])
A_d = signal.detrend(A, axis=1, type='linear')
A_d.shape

(3, 10)

In [101]:
# Test the xarray.concat option
N = 10
times1 = np.arange(N)
times2 = np.arange(N)+8
data1 = times1*2
data2 = times2*3
da1 = xr.DataArray(data1, coords=[times1], dims=['time'])
da2 = xr.DataArray(data2, coords=[times2], dims=['time'])

In [100]:
da1

<xarray.DataArray (time: 10)>
array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9

In [102]:
da2

<xarray.DataArray (time: 10)>
array([24, 27, 30, 33, 36, 39, 42, 45, 48, 51])
Coordinates:
  * time     (time) int64 8 9 10 11 12 13 14 15 16 17

In [105]:
# Concatenation without option does not treat the problem of overlapping time coordinates
dac = xr.concat([da1,da2],dim='time')

In [106]:
dac

<xarray.DataArray (time: 20)>
array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 24, 27, 30, 33, 36, 39, 42, 45,
       48, 51])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 8 9 10 11 12 13 14 15 16 17

In [110]:
da1_a, da2_a = xr.align(da1, da2, join='outer')

In [111]:
da1_a

<xarray.DataArray (time: 18)>
array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., nan, nan, nan, nan,
       nan, nan, nan, nan])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17

In [112]:
da2_a

<xarray.DataArray (time: 18)>
array([nan, nan, nan, nan, nan, nan, nan, nan, 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51.])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17

In [9]:
# Test removing discontinuities
N = 10
times1 = np.arange(N)
times2 = np.arange(N)+N
data1 = times1
data2 = times2*2
da1 = xr.DataArray(data1, coords=[times1], dims=['time'])
da2 = xr.DataArray(data2, coords=[times2], dims=['time'])
dac = xr.concat([da1,da2],dim='time')

In [10]:
dac

<xarray.DataArray (time: 20)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

In [11]:
def remove_discontinuities(da, gap):
    '''Remove discontinuities'''
    da_out = da.copy()
    diff = np.array(da[1:]) - np.array(da[:-1])
    print(diff)
    indpb = np.where(np.abs(diff) > gap)[0]
    print("### Indices at which there are discontinuities: ####")
    print(indpb)
    for k in indpb:
        da_out[k+1:] = da[k+1:] - da[k+1] + da[k]
    return da_out

In [12]:
dac_new = remove_discontinuities(dac,3)

[ 1  1  1  1  1  1  1  1  1 11  2  2  2  2  2  2  2  2  2]
### Indices at which there are discontinuities: ####
[9]


In [14]:
dac_new

<xarray.DataArray (time: 20)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  9, 11, 13, 15, 17, 19, 21, 23,
       25, 27])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

In [34]:
timeUTa = np.arange(20)
year_min = 5
year_max = 15
indt = np.where((timeUTa >= year_min) & (timeUTa < year_max))[0]
#indt = np.where(timeUTa >= year_min)[0]

In [35]:
indt

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
indt = np.asarray(timeUTa >= year_min).nonzero()
indt = np.asarray(timeUTa[indt] <= year_max).nonzero()

In [27]:
indt = timeUTa[(timeUTa >= year_min) & (timeUTa <= year_max)]

In [28]:
indt

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
indt[0]

5

In [48]:
years = xr.DataArray(np.arange(len(dac)), dims=['time'])
dac.coords['year'] = years
dac

<xarray.DataArray (time: 20)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
    year     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

In [40]:
np.arange(len(dac))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
dac.time

<xarray.DataArray 'time' (time: 20)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])
Coordinates:
  * time     (time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19